name: Unit Tests

on:
  push:
  pull_request:

jobs:
  Tests:
    name: Unit Tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
    continue-on-error: ${{ matrix.php == '8.2' }}
    steps:
      - name: Check out Source Code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Install Dependencies with Composer
        run: composer install --ignore-platform-req=php+

      - name: Unit Tests
        run: vendor/bin/phpunit --testdox
